import { defineConfig } from 'oxlint'

export default defineConfig({
  plugins: ['unicorn', 'typescript', 'oxc', 'import', 'node', 'promise'],
  categories: {
    correctness: 'error',
    suspicious: 'warn',
  },
  env: {
    builtin: true,
    es2024: true,
    node: true,
  },
  ignorePatterns: [
    'node_modules/**',
    'coverage/**',
    'dist/**',
    'compat/test/**',
    'compat/types/**',
    'src/defs.ts',
  ],
  rules: {
    eqeqeq: 'error',
    curly: ['error', 'multi'],
    yoda: 'error',
    'prefer-object-spread': 'error',
    'prefer-template': 'warn',
    'prefer-rest-params': 'error',
    'prefer-destructuring': 'warn',
    'prefer-exponentiation-operator': 'error',
    'operator-assignment': 'warn',
    'new-cap': 'error',
    'no-multi-assign': 'error',
    'no-nested-ternary': 'warn',
    'no-duplicate-imports': 'error',
    'no-template-curly-in-string': 'error',
    'no-lone-blocks': 'error',
    'no-labels': 'error',
    'no-extra-label': 'error',
    'no-else-return': 'warn',
    'no-constructor-return': 'error',
    'no-self-compare': 'error',
    'no-var': 'error',
    'no-debugger': 'error',
    'prefer-const': 'error',

    'accessor-pairs': 'error',
    'array-callback-return': 'error',
    'no-array-constructor': 'error',
    'no-case-declarations': 'error',
    'no-fallthrough': 'error',
    'no-new-wrappers': 'error',
    'no-object-constructor': 'error',
    'no-prototype-builtins': 'error',
    'no-redeclare': 'error',
    'no-throw-literal': 'error',
    'no-useless-return': 'error',
    'symbol-description': 'error',
    'default-case-last': 'error',
    'default-param-last': 'error',
    'no-multi-str': 'error',
    'no-new-func': 'error',
    'no-return-assign': 'error',
    'no-useless-computed-key': 'error',
    'prefer-promise-reject-errors': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-new': 'error',
    'no-unexpected-multiline': 'error',
    'no-unneeded-ternary': 'error',
    'no-useless-constructor': 'error',
    'no-iterator': 'error',
    'no-proto': 'error',
    'no-regex-spaces': 'error',
    'no-sequences': 'error',
    'no-void': 'error',
    'unicode-bom': 'error',
    'no-eval': 'error',
    'no-caller': 'error',
    'no-with': 'error',
    'no-unused-expressions': 'error',
    'no-useless-rename': 'error',
    'no-extra-boolean-cast': 'error',

    'unicorn/prefer-string-starts-ends-with': 'error',
    'unicorn/prefer-string-trim-start-end': 'error',
    'unicorn/prefer-string-slice': 'warn',
    'unicorn/prefer-spread': 'error',
    'unicorn/prefer-includes': 'error',
    'unicorn/prefer-array-flat-map': 'warn',
    'unicorn/prefer-optional-catch-binding': 'error',
    'unicorn/prefer-negative-index': 'warn',
    'unicorn/prefer-structured-clone': 'warn',
    'unicorn/prefer-node-protocol': 'error',
    'unicorn/no-negated-condition': 'warn',
    'unicorn/no-typeof-undefined': 'warn',
    'unicorn/no-lonely-if': 'warn',
    'unicorn/no-useless-promise-resolve-reject': 'error',
    'unicorn/no-instanceof-array': 'error',
    'unicorn/throw-new-error': 'error',
    'unicorn/number-literal-case': 'error',
    'unicorn/no-zero-fractions': 'error',

    'typescript/consistent-type-definitions': 'error',
    'typescript/consistent-type-imports': 'error',
    'typescript/no-inferrable-types': 'error',
    'typescript/no-empty-interface': 'warn',
    // the interface is the original library's, and that is what its types say
    'typescript/no-explicit-any': 'off',
    'no-underscore-dangle': [
      'warn',
      { allow: ['_rpc', '_updateSecret', '_read', '_write', '_writev', '_final'] },
    ],
    'typescript/prefer-as-const': 'error',
    'typescript/prefer-optional-chain': 'warn',
    'typescript/prefer-nullish-coalescing': 'warn',
    'typescript/prefer-function-type': 'error',
    'typescript/prefer-for-of': 'warn',
    'typescript/array-type': 'error',
    'typescript/ban-ts-comment': 'error',
    'typescript/consistent-indexed-object-style': 'error',
    'typescript/no-namespace': 'error',
    'typescript/no-useless-empty-export': 'warn',
    'typescript/no-duplicate-enum-values': 'error',
    'typescript/no-mixed-enums': 'error',
    'typescript/no-unsafe-declaration-merging': 'error',

    'oxc/no-accumulating-spread': 'error',

    'import/no-duplicates': 'error',
    'import/first': 'error',
    'import/no-named-default': 'error',
    'import/no-webpack-loader-syntax': 'error',
    'import/no-absolute-path': 'error',

    'node/no-new-require': 'error',
    'node/no-exports-assign': 'error',

    'promise/param-names': 'error',
  },
})
